spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-west-3.amazonaws.com/eu-west-3_H1UTyevos
          jwk-set-uri: https://cognito-idp.eu-west-3.amazonaws.com/eu-west-3_H1UTyevos/.well-known/jwks.json
      client:
        registration:
          cognito:
            client-id: 6pv9g6ad1b0fhfo06v8g9b0alm
            client-secret: 1eudob0bpbieaus6q2edmd3qrahuj65ldd8562rccck6dtbhu4rd
            scope:
              - email
              - openid
              - phone
            # Spring Security by default uses a redirect-uri in the format: {baseUrl}/login/oauth2/code/{registrationId}
            # For example: http://localhost:8080/login/oauth2/code/cognito
            # See more: https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-sample-redirect-uri
  mail:
    host: smtp.mailgun.org
    port: 587
    username: postmaster@sandboxef78bc798ab847fdbcb10955b9f9d821.mailgun.org
    password: 7d190a5122c013a8d802230942c477a9-f55d7446-6171ad18
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: noreply@sandboxef78bc798ab847fdbcb10955b9f9d821.mailgun.org
server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

cognito:
  user-pool-id: eu-west-3_H1UTyevos

aws:
  access-key: AKIARWPFIFREPHL3JBPE
  secret-key: 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
  region: eu-west-3
  cognito:
    user-pool-id: eu-west-3_H1UTyevos