services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-service:8761/actuator/health"]
      interval: 5s
      retries: 4
    networks:
      - class-network

  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "8888:8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-service:8888/actuator/health"]
      interval: 5s
      retries: 4
    depends_on:
      - discovery-service
    networks:
      - class-network

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8088:8088"
    environment:
      - CONFIG_SERVICE_URL=http://config-service:8888
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway-service:8088/actuator/health"]
      interval: 5s
      retries: 4
    depends_on:
      - config-service
    networks:
      - class-network

  admin-server:
    build: ./admin-server
    container_name: admin-server
    ports:
      - "8070:8070"
    environment:
      - CONFIG_SERVICE_URL=http://config-service:8888
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://admin-server:8070/actuator/health"]
      interval: 10s
      retries: 4
    depends_on:
      - gateway-service
    networks:
      - class-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8085:8085"
    environment:
      - CONFIG_SERVICE_URL=http://config-service:8888
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://admin-server:8070/actuator/health"]
      interval: 10s
      retries: 4
    depends_on:
      - gateway-service
    networks:
      - class-network

  university-service:
    build: ./university-service
    container_name: university-service
    ports:
      - "8081:8081"
    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://university-db:5432/university
#      - SPRING_DATASOURCE_USERNAME=class
#      - SPRING_DATASOURCE_PASSWORD=class
      - CONFIG_SERVICE_URL=http://config-service:8888
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://university-service:8081/actuator/health"]
      interval: 10s
      retries: 4
    depends_on:
      - gateway-service
    networks:
      - class-network

networks:
  class-network:
    driver: bridge

volumes:
  university-data:
