spring:
  application:
    name: university-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/university}
    username: ${SPRING_DATASOURCE_USERNAME:class}
    password: ${SPRING_DATASOURCE_PASSWORD:class}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      logging:
        sql: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: test
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  profiles:
#    active: test
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace